# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="target value",
                    ),
                ),
                (
                    "tolerance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="tolerance",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="unit"),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("SUM", "Sum"),
                            ("AVG", "Average"),
                            ("COUNT", "Count"),
                            ("LAST", "Last value"),
                            ("MIN", "Minimum"),
                            ("MAX", "Maximum"),
                        ],
                        default="SUM",
                        max_length=8,
                        verbose_name="aggregation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional scope; null means platform-wide metric.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "metric",
                "verbose_name_plural": "metrics",
            },
        ),
        migrations.CreateModel(
            name="KpiMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, default=1, max_digits=6, verbose_name="weight"
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_metrics",
                        to="metrics.kpi",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_links",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI metric",
                "verbose_name_plural": "KPI metrics",
            },
        ),
        migrations.AddField(
            model_name="kpi",
            name="metrics",
            field=models.ManyToManyField(
                related_name="kpis", through="metrics.KpiMetric", to="metrics.metric"
            ),
        ),
        migrations.CreateModel(
            name="MetricValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=4, max_digits=18, verbose_name="value"),
                ),
                ("period_start", models.DateTimeField(db_index=True, verbose_name="period start")),
                ("period_end", models.DateTimeField(verbose_name="period end")),
                ("dimension", models.JSONField(blank=True, default=dict, verbose_name="dimension")),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "verbose_name": "metric value",
                "verbose_name_plural": "metric values",
            },
        ),
        migrations.CreateModel(
            name="SLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        help_text="Requests filtering value (optional).",
                        max_length=16,
                        null=True,
                        verbose_name="priority",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("RESPONSE", "Response"), ("RESOLUTION", "Resolution")],
                        default="RESPONSE",
                        max_length=16,
                        verbose_name="scope",
                    ),
                ),
                ("target_minutes", models.PositiveIntegerField(verbose_name="target (minutes)")),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slas",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA",
                "verbose_name_plural": "SLAs",
            },
        ),
        migrations.AddConstraint(
            model_name="kpimetric",
            constraint=models.UniqueConstraint(fields=("kpi", "metric"), name="u_kpi_metric"),
        ),
        migrations.AddIndex(
            model_name="metricvalue",
            index=models.Index(
                fields=["metric", "period_start"], name="metrics_met_metric__4fd7d0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sla",
            constraint=models.UniqueConstraint(
                fields=("service", "name", "scope"), name="u_sla_name_scope"
            ),
        ),
    ]
