# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("full_name", models.CharField(max_length=255, verbose_name="full name")),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="phone"),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("CONTRACTOR", "Contractor"),
                            ("EXTERNAL_SUPPLIER", "External Supplier"),
                            ("CITIZEN", "Citizen"),
                            ("PARTNER", "Partner"),
                        ],
                        db_index=True,
                        default="CITIZEN",
                        max_length=32,
                        verbose_name="person type",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional login identity for this person.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
        migrations.CreateModel(
            name="PersonSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="BASIC",
                        max_length=16,
                        verbose_name="level",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="verified at"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="people.person",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person that certified this skill.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_skills",
                        to="people.person",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_links",
                        to="people.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "person skill",
                "verbose_name_plural": "person skills",
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["person_type", "active"], name="people_pers_person__2dec83_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email",),
                name="u_person_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="personskill",
            constraint=models.UniqueConstraint(fields=("person", "skill"), name="u_person_skill"),
        ),
    ]
