# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "service capability",
                "verbose_name_plural": "service capabilities",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("DEGRADED", "Degraded"),
                            ("DISRUPTED", "Disrupted"),
                            ("PAUSED", "Paused"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="OPERATIONAL",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
        migrations.CreateModel(
            name="ServiceActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("INTERNAL", "Internal"), ("EXTERNAL", "External")],
                        default="INTERNAL",
                        max_length=16,
                        verbose_name="actor type",
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="responsibility"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional specific person; blank means 'anyone with the role'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_actor_links",
                        to="people.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_actors",
                        to="access.role",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actors",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "service actor",
                "verbose_name_plural": "service actors",
            },
        ),
        migrations.CreateModel(
            name="ServiceCapabilityAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("required", models.BooleanField(default=True, verbose_name="required")),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="services.servicecapability",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_links",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "service capability assignment",
                "verbose_name_plural": "service capability assignments",
            },
        ),
        migrations.AddField(
            model_name="servicecapability",
            name="services",
            field=models.ManyToManyField(
                related_name="capabilities",
                through="services.ServiceCapabilityAssignment",
                to="services.service",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["organization", "active"], name="services_se_organiz_8d8045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["status", "active"], name="services_se_status_50ecf6_idx"),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="u_service_org_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceactor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", False)),
                fields=("service", "role", "person"),
                name="u_service_actor_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceactor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", True)),
                fields=("service", "role"),
                name="u_service_actor_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecapabilityassignment",
            constraint=models.UniqueConstraint(
                fields=("service", "capability"), name="u_service_capability"
            ),
        ),
    ]
