# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE", "Vehicle"),
                            ("EQUIPMENT", "Equipment"),
                            ("MATERIAL", "Material"),
                            ("FACILITY", "Facility"),
                            ("SUPPLIER", "Supplier"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="resource type",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "code",
                    models.SlugField(blank=True, max_length=64, null=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="organizations.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "resource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resources.resource",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="serial number",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="purchase date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("MAINTENANCE", "In Maintenance"),
                            ("RETIRED", "Retired"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
            },
            bases=("resources.resource",),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "resource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resources.resource",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="quantity on hand"
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="unit"),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="reorder level",
                    ),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
            },
            bases=("resources.resource",),
        ),
        migrations.CreateModel(
            name="ResourceAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "label",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="label"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="started at"),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="ended at")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="resources.resource",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "resource assignment",
                "verbose_name_plural": "resource assignments",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resources.asset",
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="equipment type"
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="capacity"
                    ),
                ),
            ],
            options={
                "verbose_name": "equipment",
                "verbose_name_plural": "equipment",
            },
            bases=("resources.asset",),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["organization", "resource_type"], name="resources_r_organiz_00cc02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type", "active"], name="resources_r_resourc_d899b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceassignment",
            index=models.Index(
                fields=["resource", "ended_at"], name="resources_r_resourc_9ea03f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceassignment",
            index=models.Index(
                fields=["target_type", "target_id"], name="resources_r_target__150d6e_idx"
            ),
        ),
    ]
