# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
        ("requests", "0001_initial"),
        ("services", "0001_initial"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_requests",
                to="workflows.workflow",
            ),
        ),
        migrations.AddField(
            model_name="requestcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_comments",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="requestcomment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="requests.request",
            ),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_types",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="request_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="requests.requesttype",
            ),
        ),
        migrations.AddIndex(
            model_name="requestcomment",
            index=models.Index(
                fields=["request", "created_at"], name="requests_re_request_ec0a47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["service", "status"], name="requests_re_service_cddd20_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["assigned_to", "status"], name="requests_re_assigne_5a6f75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["requester", "status"], name="requests_re_request_100d86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["priority", "status"], name="requests_re_priorit_46b6de_idx"
            ),
        ),
    ]
