# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0002_initial"),
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                ("reason", models.TextField(blank=True, default="", verbose_name="reason")),
                (
                    "risk",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                        default="MEDIUM",
                        max_length=16,
                        verbose_name="risk",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROPOSED", "Proposed"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("IMPLEMENTED", "Implemented"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "planned_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="planned start"),
                ),
                (
                    "planned_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="planned end"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used when the change targets the organization itself.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changes_requested",
                        to="people.person",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "change",
                "verbose_name_plural": "changes",
            },
        ),
        migrations.CreateModel(
            name="ChangeApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="decision",
                    ),
                ),
                ("comment", models.TextField(blank=True, default="", verbose_name="comment")),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="decided at"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_approvals",
                        to="people.person",
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="changes.change",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_approvals",
                        to="access.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "change approval",
                "verbose_name_plural": "change approvals",
            },
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(fields=["service", "status"], name="changes_cha_service_22fc2d_idx"),
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                fields=["organization", "status"], name="changes_cha_organiz_66f254_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(fields=["risk", "status"], name="changes_cha_risk_87d503_idx"),
        ),
        migrations.AddConstraint(
            model_name="changeapproval",
            constraint=models.UniqueConstraint(
                fields=("change", "approver"), name="u_change_approver"
            ),
        ),
    ]
