# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("people", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("DIAGNOSED", "Diagnosed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                        verbose_name="priority",
                    ),
                ),
                ("root_cause", models.TextField(blank=True, default="", verbose_name="root cause")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problems_assigned",
                        to="people.person",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="problems",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "problem",
                "verbose_name_plural": "problems",
            },
        ),
        migrations.CreateModel(
            name="ProblemIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_links",
                        to="incidents.incident",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_links",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "problem incident",
                "verbose_name_plural": "problem incidents",
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["service", "status"], name="problems_pr_service_2859ed_idx"),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["assigned_to", "status"], name="problems_pr_assigne_ec0a89_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="problemincident",
            constraint=models.UniqueConstraint(
                fields=("problem", "incident"), name="u_problem_incident"
            ),
        ),
    ]
