# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("people", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="version")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="DRAFT",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("REQUEST", "Request"), ("EVENT", "Event")],
                        default="MANUAL",
                        max_length=32,
                        verbose_name="trigger",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to="people.person",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow",
                "verbose_name_plural": "workflows",
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("START", "Start"),
                            ("TASK", "Task"),
                            ("GATEWAY", "Gateway"),
                            ("APPROVAL", "Approval"),
                            ("END", "End"),
                        ],
                        default="TASK",
                        max_length=16,
                        verbose_name="step type",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "sla_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Deadline for this step.",
                        null=True,
                        verbose_name="SLA (minutes)",
                    ),
                ),
                (
                    "required_inputs",
                    models.JSONField(blank=True, default=list, verbose_name="required inputs"),
                ),
                ("outputs", models.JSONField(blank=True, default=list, verbose_name="outputs")),
                (
                    "responsible_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role that performs this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_steps",
                        to="access.role",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow step",
                "verbose_name_plural": "workflow steps",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("WAITING", "Waiting"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("subject_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_executions_created",
                        to="people.person",
                    ),
                ),
                (
                    "subject_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_executions",
                        to="workflows.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow execution",
                "verbose_name_plural": "workflow executions",
            },
        ),
        migrations.CreateModel(
            name="WorkflowTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("BLOCKED", "Blocked"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True, verbose_name="deadline")),
                ("result", models.JSONField(blank=True, null=True, verbose_name="result")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_tasks",
                        to="people.person",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workflows.workflowexecution",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_tasks",
                        to="workflows.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow task",
                "verbose_name_plural": "workflow tasks",
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="name"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("condition", models.JSONField(blank=True, null=True, verbose_name="condition")),
                (
                    "from_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="workflows.workflowstep",
                    ),
                ),
                (
                    "to_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="workflows.workflowstep",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow transition",
                "verbose_name_plural": "workflow transitions",
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["service", "status"], name="workflows_w_service_1d967c_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["status", "trigger"], name="workflows_w_status_27648f_idx"),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.UniqueConstraint(
                fields=("service", "name", "version"), name="u_workflow_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstep",
            constraint=models.UniqueConstraint(
                fields=("workflow", "code"), name="u_workflow_step_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstep",
            constraint=models.UniqueConstraint(
                fields=("workflow", "order"), name="u_workflow_step_order"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="workflows_w_workflo_f6053d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "started_at"], name="workflows_w_status_9f5713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["assigned_to", "status"], name="workflows_w_assigne_1b0e2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["execution", "status"], name="workflows_w_executi_0bb8a6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtransition",
            constraint=models.UniqueConstraint(
                fields=("workflow", "from_step", "order"), name="u_transition_order"
            ),
        ),
    ]
