# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("organizations", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaccess",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_access",
                to="organizations.organizationmembership",
            ),
        ),
        migrations.AddField(
            model_name="serviceaccess",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_access",
                to="services.service",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="u_role_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceaccess",
            constraint=models.UniqueConstraint(
                fields=("membership", "service"), name="u_membership_service"
            ),
        ),
    ]
