# Generated by Django 5.2.17 on 2026-09-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="role",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
