# Generated by Django 5.2.17 on 2026-09-06 21:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        CreateExtension("ltree"),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("DISTRICT", "District"),
                            ("MUNICIPALITY", "Municipality"),
                            ("PARISH", "Parish"),
                            ("DEPARTMENT", "Department"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=32,
                        verbose_name="organization type",
                    ),
                ),
                (
                    "path",
                    apps.common.fields.LTreeField(
                        blank=True, editable=False, null=True, verbose_name="path"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent organizational unit. Null for the root.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ("path",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="people.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="access.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization membership",
                "verbose_name_plural": "organization memberships",
            },
        ),
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                (
                    "path",
                    apps.common.fields.LTreeField(
                        blank=True, editable=False, null=True, verbose_name="path"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organizations.organizationunit",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_units",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization unit",
                "verbose_name_plural": "organization units",
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["path"], name="org_path_gin_idx", opclasses=["gist_ltree_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("parent", "code"), name="u_organization_parent_code"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "role"], name="organizatio_organiz_f7570b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["person", "role"], name="organizatio_person__46f461_idx"),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("person", "organization", "role"), name="u_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationunit",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["path"], name="unit_path_gin_idx", opclasses=["gist_ltree_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationunit",
            constraint=models.UniqueConstraint(
                fields=("organization", "parent", "code"), name="u_unit_org_parent_code"
            ),
        ),
    ]
