# Generated by Django 5.2.17 on 2026-09-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("COUNTRY", "Country"),
                    ("DISTRICT", "District"),
                    ("MUNICIPALITY", "Municipality"),
                    ("PARISH", "Parish"),
                    ("DEPARTMENT", "Department"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=32,
                verbose_name="organization type",
            ),
        ),
    ]
